### ISSUE TITLE
Error installing: "unknown file type: .themes/simple/sass/."

### ISSUE THREAD

**Issue by brunzino** [chuguixin/Simple#1]
I like the screenshot on http://octopressthemes.github.io/ and would like to install this theme, but when I run the install command, I get: 

```
$ rake install['simple']
A theme is already installed, proceeding will overwrite existing files. Are you sure? [y/n] y
## Copying simple theme into ./source and ./sass
mkdir -p source
cp -r .themes/simple/source/. source
mkdir -p sass
cp -r .themes/simple/sass/. sass
rake aborted!
unknown file type: .themes/simple/sass/.
```

I am new to Octopress, is there a different install command?

**Comment by chuguixin** [comment]
oh, i am sorry for that.
this theme now is for [hexo.io](http://hexo.io) not Octopress,the old one for Octopress is now at [simple-Octopress](https://github.com/chuguixin/Simple-Octopress)。
thx

**Comment by brunzino** [comment]
Cool, thanks!
